In [10]:
from roboflow import Roboflow
import open3d as o3d
import numpy as np
import math
import pyransac3d as pyrsc

In [11]:
show_pcl = True

In [12]:
def visualizer(cloud):

    if type(cloud) != list:
        cloud = [cloud]

    if show_pcl:
        # point cloud
        center_of_mass = np.mean(np.asarray(cloud[0].points), axis=0)
    
        o3d.visualization.draw_geometries(cloud,
                                    zoom=0.57899999999999985,
                                    front=  [ 0.053781796277127751, 0.99511863815317547, 0.082743062484869914 ],
                                    up =  [ -0.99452345262671604, 0.045944145215534776, 0.093873519673282182 ],
                                    lookat=[ 0.14950467828195535, -0.21448131248991498, 0.63221199653621662 ])
    
    else:
        pass

In [51]:
# pcd = o3d.io.read_point_cloud("3dmodels/Data/Data 12.ply")
pcd1 = o3d.io.read_point_cloud("3dmodels/Data/Data 11 Photogrammetry.ply")

visualizer([pcd1])

In [6]:
pcd = pcd.uniform_down_sample(75)

In [6]:
mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=pcd.get_center())

visualizer([pcd, mesh_frame])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current

In [1]:
from PIL import Image
import os

# Get list of HEIF and HEIC files in directory
directory = './images_2'
files = [f for f in os.listdir(directory) if f.endswith('.heic') or f.endswith('.heif')]
# Convert each file to JPEG
for filename in files:
    image = Image.open("images_2/1720793918611481.heif")
    image.save(os.path.join(directory, os.path.splitext(filename)[0] + '.png'))

UnidentifiedImageError: cannot identify image file 'C:\\Users\\vmuriki3\\Documents\\test_code\\images_2\\1720793918611481.heif'

In [8]:
import imageio
import os

directory = './images_2'
directory1 = './output'
files = [f for f in os.listdir(directory) if f.endswith('.heic') or f.endswith('.heif')]
# Convert each file to PNG
for filename in files:
    image = imageio.imread(os.path.join(directory, filename))
    imageio.imwrite(os.path.join(directory1, os.path.splitext(filename)[0] + '.png'), image)


1720794058522447.heif
1720794059393643.heif
1720794060119187.heif
1720794060859396.heif
1720794061608688.heif
1720794062680007.heif
1720794063388191.heif
1720794064088356.heif
1720794064786588.heif
1720794065494503.heif


In [9]:


def remind_me():
    # Create a Tkinter root window
    root = tk.Tk()
    root.withdraw()  # Hide the main window

    # Show a message box with a reminder
    messagebox.showinfo("Reminder", "Don't forget to do your task!")

    # Close the root window
    root.destroy()

# Example usage:
remind_me()


In [ ]:
import numpy as np

# Assuming check_grid and img are NumPy arrays and col is defined

# Ensure check_grid is boolean for proper logical operations
check_grid = check_grid.astype(bool)

# Calculate ranges
dx_range = np.arange(-resolution, resolution)
dz_range = np.arange(-resolution, resolution)

# Calculate new coordinates
x_coords, z_coords = np.meshgrid(x_c + dx_range, z_c + dz_range, indexing='ij')

# Flatten coordinates for easier masking
x_coords_flat = x_coords.flatten()
z_coords_flat = z_coords.flatten()

# Create valid masks for coordinates
valid_x = (0 <= x_coords_flat) & (x_coords_flat < shape1)
valid_z = (0 <= z_coords_flat) & (z_coords_flat < shape2)

# Combine valid masks
valid_indices = valid_x & valid_z

# Check grid values at valid coordinates
check_grid_values = check_grid[x_coords_flat[valid_indices], z_coords_flat[valid_indices]]
update_mask = ~check_grid_values  # Invert boolean values

# Apply updates
update_indices = valid_indices[~check_grid_values]
check_grid[x_coords_flat[update_indices], z_coords_flat[update_indices]] = 1
img[x_coords_flat[update_indices], z_coords_flat[update_indices]] = col


In [ ]:
# for dx in range(-resolution, resolution, 1):
#     for dz in range(-resolution, resolution, 1):

#         if 0 <= x_c + dx < shape1 and 0 <= z_c + dz < shape2: #If it is in bounds with the image shapes
#             if not check_grid[x_c + dx, z_c + dz]:
#                 check_grid[x_c + dx, z_c + dz] = 1
#                 img[x_c + dx, z_c + dz] = col

In [248]:
resolution = 2
x, y = 5, 5
max_x, max_y = 10, 10
dx_l = np.linspace(-resolution+x, resolution+x, 2*resolution+1, dtype=int)
dy_l = np.linspace(-resolution+y, resolution+y, 2*resolution+1, dtype=int)
print(dx_l, dy_l)

[3 4 5 6 7] [3 4 5 6 7]


In [269]:
check_grid = np.zeros((10, 10), dtype=int)
check_grid

check_grid[5, 5] = 1
check_grid[5, 6] = 1
check_grid

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [251]:
dx, dy = np.meshgrid(dx_l, dy_l)
dx, dy

(array([[3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7]]),
 array([[3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7]]))

In [252]:
# dx_t = (dx >= 0) & (dx < max_x)
# dy_t = (dy >= 0) & (dy < max_y)
# dx_t, dy_t

(array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]))

In [212]:
np.argwhere(dy_t)[::-1][0]

array([3, 4], dtype=int64)

In [226]:
# x_min = dx[np.argwhere(dx_t)[0][0], np.argwhere(dx_t)[0][1]]
# x_max = dx[np.argwhere(dx_t)[::-1][0][0], np.argwhere(dx_t)[::-1][0][1]]

# y_min = dy[np.argwhere(dy_t)[0][0], np.argwhere(dy_t)[0][1]]
# y_max = dy[np.argwhere(dy_t)[::-1][0][0], np.argwhere(dy_t)[::-1][0][1]]

# x_min, x_max, y_min, y_max

(0, 4, 0, 4)

In [253]:
temp_check_grid = check_grid[min(dx_l):max(dx_l)+1, min(dy_l):max(dy_l)+1]
temp_check_grid

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [254]:
dx1 = (dx >= 0) & (dx < max_x) & ~temp_check_grid
dy1 = (dy >= 0) & (dy < max_y) & ~temp_check_grid
dx_dy = dx1 & dy1
dx1, dy1, dx_dy

(array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=int32),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=int32),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 0, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=int32))

In [270]:
ones = np.argwhere(dx_dy)
ones[:, 0] += 3
ones[:, 1] += 3
# ones

In [273]:
ones

array([[3, 3],
       [3, 4],
       [3, 5],
       [3, 6],
       [3, 7],
       [4, 3],
       [4, 4],
       [4, 5],
       [4, 6],
       [4, 7],
       [5, 3],
       [5, 4],
       [5, 7],
       [6, 3],
       [6, 4],
       [6, 5],
       [6, 6],
       [6, 7],
       [7, 3],
       [7, 4],
       [7, 5],
       [7, 6],
       [7, 7]], dtype=int64)

In [271]:
check_grid

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [272]:
check_grid[ones[:, 0], ones[:, 1]] = 1
check_grid

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [119]:
result1 = (result >= 0) and (result)
result1

array([[[False,  True],
        [False,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[False,  True],
        [False,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[False,  True],
        [False,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[False,  True],
        [False,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[False,  True],
        [False,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]]])

In [78]:
# X -> Row and Y -> Column

In [82]:
grid[0] + y, grid[1] + x

(array([[0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6],
        [0, 1, 2, 3, 4, 5, 6]]),
 array([[-1, -1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5,  5,  5]]))